name: leaveapproval
run-name: Setting up the leaveapproval database
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Test Output
      run: echo "Here is a test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show databases
      run: mysql -h localhost --port 3306 -u root -p -e "SHOW DATABASES";
    - name: Run a sample SQL on remote
      run: mysql -h localhost --port 3306 -u root -p -e "webdevops/leaveapproval.sql";
      
